parameters:
  check:
    value: "true"
    description: "test param"
shared:
  image: node:20
jobs:
  hub:
    requires: ~commit
    steps:
      - echo: echo hub
  A:
    requires: hub
    steps:
      - wait: sleep 100
      - echo: echo hub
  B:
    requires: hub
    steps:
      - echo: echo hub
  C:
    requires: hub
    steps:
      - echo: echo hub
  D:
    requires: hub
    steps:
      - check: |
          export CHECK=`meta get parameters.check.value`
          if "${CHECK}"; then exit 1; fi
      - echo: echo hub
  TARGET:
    requires: [A,B,C,D]
    steps:
      - echo: echo hub
