parameters:
  check:
    value: "0"
    description: "test param"
shared:
  image: node:20
jobs:
  hub:
    requires: ~commit
    steps:
      - echo: echo hub
  A:
    requires: hub
    steps:
      - echo: echo hub
  B:
    requires: hub
    steps:
      - echo: echo hub
  C:
    requires: hub
    steps:
      - echo: echo hub
  D:
    requires: hub
    steps:
      - check: |
          CHECK=$(meta get parameters.check)
          if [ "$CHECK" = "0" ]; then exit 1; fi
      - echo: echo hub
  TARGET:
    requires: [A,B,C,D]
    steps:
      - echo: echo hub
